// Code generated by cmd/cgo; DO NOT EDIT.

package main

import "unsafe"

import _ "runtime/cgo"

import "syscall"

var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
type _Ctype_TestS = _Ctype_struct___0

type _Ctype_int int32

type _Ctype_struct___0 struct {
	a _Ctype_int
}

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgo_runtime_cgocallback runtime.cgocallback
func _cgo_runtime_cgocallback(unsafe.Pointer, unsafe.Pointer, uintptr, uintptr)

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
func _cgoCheckPointer(interface{}, ...interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
func _cgoCheckResult(interface{})

//go:cgo_export_dynamic GoAdder2
//go:linkname _cgoexp_406de6e2c283_GoAdder2 _cgoexp_406de6e2c283_GoAdder2
//go:cgo_export_static _cgoexp_406de6e2c283_GoAdder2
//go:nosplit
//go:norace
func _cgoexp_406de6e2c283_GoAdder2(a unsafe.Pointer, n int32, ctxt uintptr) {
	fn := _cgoexpwrap_406de6e2c283_GoAdder2
	_cgo_runtime_cgocallback(**(**unsafe.Pointer)(unsafe.Pointer(&fn)), a, uintptr(n), ctxt);
}

func _cgoexpwrap_406de6e2c283_GoAdder2(p0 *_Ctype_struct___0, p1 *_Ctype_struct___0) (r0 int) {
	return GoAdder2(p0, p1)
}
//go:cgo_export_dynamic GoAdder
//go:linkname _cgoexp_406de6e2c283_GoAdder _cgoexp_406de6e2c283_GoAdder
//go:cgo_export_static _cgoexp_406de6e2c283_GoAdder
//go:nosplit
//go:norace
func _cgoexp_406de6e2c283_GoAdder(a unsafe.Pointer, n int32, ctxt uintptr) {
	fn := _cgoexpwrap_406de6e2c283_GoAdder
	_cgo_runtime_cgocallback(**(**unsafe.Pointer)(unsafe.Pointer(&fn)), a, uintptr(n), ctxt);
}

func _cgoexpwrap_406de6e2c283_GoAdder(p0 int, p1 int) (r0 int) {
	return GoAdder(p0, p1)
}
