// Code generated by cmd/cgo; DO NOT EDIT.

//line adder.go:1:1
package main

import "fmt"

// #include "../test.h"
import _ "unsafe"

//export GoAdder2
func GoAdder2(x, y *_Ctype_struct___0) int {
	fmt.Printf("Go says: adding %v and %v\n", x, y)
	return x.a + y.a
}

//export GoAdder
func GoAdder(x, y int) int {
	fmt.Printf("Go says: adding %v and %v\n", x, y)
	return x + y
}

func main() {} // Required but ignored
